package quynh.java.webapp.pm.util.plantuml;

public class DiagramSampleText {

	public static final String INPUT_MIND_MAP_TEXT = "ASM\n"
			+ "\n"
			+ "* 4.Location\n"
			+ "** Memory Model\n"
			+ "** Vegetarian\n"
			+ "** Less processed foods\n"
			+ "** Buy local food\n"
			+ "* Travel\n"
			+ "** Bike more\n"
			+ "** Ride buses\n"
			+ "** Buy an electric car\n"
			+ "\n"
			+ "* Home\n"
			+ "** Energy audit\n"
			+ "** Use a cloths line\n"
			+ "** Add insulation\n"
			+ "** Get solar panels\n"
			+ "* Be a role model abc acb alkdsll dslfdsljfjsdlfsdljf\n"
			+ "** Vote\n"
			+ "** Encourage others role model abc acb alkdsll dslfdsljfjsdlfsdlj\n"
			+ "*** Teach your kids to eat icream\n"
			+ "** Teach your kids\n";
	public static final String diagram = "@startmindmap\n"
			+ "\n"
			+ "'Compatible with OrgMode \n"
			+ "\n"
			+ "* ASM\n"
			+ "\n"
			+ "** 4.Location\n"
			+ "*** Memory Model\n"
			+ "*** Vegetarian\n"
			+ "*** Less processed foods and more sometime and it is the name\n"
			+ "**** abc\n"
			+ "*** Buy local food\n"
			+ "** Travel\n"
			+ "*** Bike more\n"
			+ "*** Ride buses\n"
			+ "*** Buy an electric car\n"
			+ "\n"
			+ "left side\n"
			+ "\n"
			+ "** Home\n"
			+ "*** Energy audit\n"
			+ "*** Use a cloths line\n"
			+ "*** Add insulation\n"
			+ "*** Get solar panels\n"
			+ "** Be a role model\n"
			+ "*** Vote\n"
			+ "\n"
			+ "@endmindmap";
	public static final String activity = "@startuml\n"
			+ "start\n"
			+ "\n"
			+ "if (Graphviz installed?) then (yes)\n"
			+ "  :process all\\ndiagrams;\n"
			+ "else (no)\n"
			+ "  :process only\n"
			+ "  __sequence__ and __activity__ diagrams;\n"
			+ "endif\n"
			+ "\n"
			+ "stop\n"
			+ "@enduml";
}
